### ISSUE TITLE
npm failed

### ISSUE THREAD

**Issue by janeshum** [Peroluo/create-skeleton#1]
when I npm install it, report error like blower

npm i create-skeleton-quickly -g
npm WARN deprecated fast-install-puppeteer@1.0.5: this package have been archived. please install the @all-in-js/fast-install-puppeteer instead.
/Users/user/.nvm/versions/node/v12.18.3/bin/csq -> /Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/create-skeleton-quickly/bin/index.js

> fast-install-puppeteer@1.0.5 install /Users/user/.nvm/versions/node/v12.18.3/lib/node_modules/create-skeleton-quickly/node_modules/fast-install-puppeteer
> node src/index.js

[fast-install-puppeteer]: I will use yarn.
[fast-install-puppeteer]: ready to download puppeteer@latest.
[fast-install-puppeteer]: use mirror: https://npm.taobao.org/mirrors.
[fast-install-puppeteer]: use registry: https://registry.npm.taobao.org/.
yarn run v1.22.10
$ cross-env PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors yarn add puppeteer@latest --registry https://registry.npm.taobao.org/ --prefer-offline
[1/4] 🔍  Resolving packages...
**error Couldn't find a package.json file in "/Users/user/Library/Caches/Yarn/v6/npm-test-job-0.1.0-c5e003bf-e0ff-4300-b93c-6547ee78cfd6-1620620976076/node_modules/test-job"**
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
**error Command failed with exit code 1.**
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[fast-install-puppeteer]: puppeteer@latest has installed, enjoy your work.
+ create-skeleton-quickly@0.0.2
added 96 packages from 57 contributors in 14.032s

-------------------------------------------------------------------------------------------------------------------------

 I see that need install the package "fast-install-puppeteer", but NPM show it 

"This package has been deprecated
Author message:
this package have been archived. please install the @all-in-js/fast-install-puppeteer instead."

**Comment by aliraza944** [comment]
What version of Node JS are you using?

**Comment by luoguoxiong** [comment]
is ok
